services:
  redis:
    image: redis:7.4-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
      - "6380:6380"
    volumes:
      - redis_data:/data
    networks:
      - codexion-network

volumes:
  redis_data:

networks:
  codexion-network:
    external: true
