import type { MasterDataModuleDefinition } from '../../../../foundation/master-record/domain/value-objects/master-data-definition.js'

export const auditorClientDefinition: MasterDataModuleDefinition = {
  key: 'auditorClients',
  label: 'Auditor Clients',
  kind: 'master',
  tableName: 'masters_auditor_clients',
  defaultSortKey: 'name',
  idPrefix: 'auditor-client',
  group: 'auditor',
  columns: [
    { key: 'name', label: 'Name', type: 'string', required: true, nullable: false },
    { key: 'group_name', label: 'Group', type: 'string', nullable: true },
    { key: 'contact_person', label: 'Contact Person', type: 'string', nullable: true },
    { key: 'mobile', label: 'Mobile', type: 'string', nullable: true },
    { key: 'whatsapp', label: 'Whatsapp', type: 'string', nullable: true },
    { key: 'email', label: 'Email', type: 'string', nullable: true },
    { key: 'gstin', label: 'GSTIN', type: 'string', nullable: true },
    { key: 'address_line_1', label: 'Address Line 1', type: 'string', nullable: true },
    { key: 'address_line_2', label: 'Address Line 2', type: 'string', nullable: true },
    { key: 'city_id', label: 'City ID', type: 'string', nullable: true },
    { key: 'city', label: 'City', type: 'string', nullable: true },
    { key: 'state_id', label: 'State ID', type: 'string', nullable: true },
    { key: 'state', label: 'State', type: 'string', nullable: true },
    { key: 'pincode_id', label: 'Pincode ID', type: 'string', nullable: true },
    { key: 'pincode', label: 'Pincode', type: 'string', nullable: true },
    { key: 'gst_user', label: 'GST User', type: 'string', nullable: true },
    { key: 'gst_pass', label: 'GST Pass', type: 'string', nullable: true },
    { key: 'einvoice_user', label: 'E-Invoice User', type: 'string', nullable: true },
    { key: 'einvoice_pass', label: 'E-Invoice Pass', type: 'string', nullable: true },
    { key: 'eway_user', label: 'E-Way User', type: 'string', nullable: true },
    { key: 'eway_pass', label: 'E-Way Pass', type: 'string', nullable: true },
    { key: 'einvoice_api_user', label: 'E-Invoice API User', type: 'string', nullable: true },
    { key: 'einvoice_api_pass', label: 'E-Invoice API Pass', type: 'string', nullable: true },
    { key: 'eway_api_user', label: 'E-Way API User', type: 'string', nullable: true },
    { key: 'eway_api_pass', label: 'E-Way API Pass', type: 'string', nullable: true },
    { key: 'email_account_user', label: 'E-mail Account User', type: 'string', nullable: true },
    { key: 'email_account_pass', label: 'E-mail Account Pass', type: 'string', nullable: true },
  ],
}
