export type LiveClientIndustry =
  | 'auditor_office'
  | 'shared_billing'
  | 'offset_printing'
  | 'garment_manufacturing'
  | 'fabric_trading'
  | 'upvc'
  | 'ecommerce'
  | 'sports_club'
  | 'garment_testing_lab'
  | 'business_connect'

export interface LiveClientScope {
  code: number
  slug: string
  name: string
  corporateId: string
  industry: LiveClientIndustry
  industryName: string
  database: string
  domains: string[]
  companies: string[]
  apps: string[]
  landingApp: string
  requirements: string[]
  notes: string
}

export const liveClientScopes: LiveClientScope[] = [
  {
    code: 100,
    slug: 'aaran_associates',
    name: 'Aaran Associates',
    corporateId: 'AARAN_ASSOCIATES',
    industry: 'auditor_office',
    industryName: 'Auditor Office / Software Back Office',
    database: 'aaran_associates_db',
    domains: ['aaran.codexsun.com', 'office.codexsun.com', 'aaran.local'],
    companies: ['Aaran Associates'],
    apps: ['application', 'billing', 'taskmanager', 'crm', 'sites', 'auditor'],
    landingApp: 'auditor',
    requirements: ['auditor-office', 'client-assist', 'gst-follow-up', 'software-back-office'],
    notes: 'Auditor office and back-office team who maintains and assists CXSun clients.',
  },
  {
    code: 101,
    slug: 'codexsun',
    name: 'CODEXSUN Shared Billing',
    corporateId: 'CODEXSUN',
    industry: 'shared_billing',
    industryName: 'Shared Billing Platform',
    database: 'codexsun_db',
    domains: ['codexsun.com', 'www.codexsun.com', 'codexsun.local'],
    companies: ['CODEXSUN'],
    apps: ['application', 'billing', 'sites'],
    landingApp: 'billing',
    requirements: ['shared-domain-billing', 'subdomain-routing', 'nginx-ready'],
    notes: 'Shared billing tenant used by clients before moving to subdomain or client-owned domains.',
  },
  {
    code: 102,
    slug: 'sri_ganapathi_printing',
    name: 'Sri Ganapathi Printing Press',
    corporateId: 'SRI_GANAPATHI',
    industry: 'offset_printing',
    industryName: 'Offset Printing',
    database: 'sri_ganapathi_printing_db',
    domains: ['sriganapathi.codexsun.com', 'ganapathi.local'],
    companies: ['Sri Ganapathi Printing Press'],
    apps: ['application', 'billing', 'accounts', 'inventory', 'offset'],
    landingApp: 'billing',
    requirements: ['simple-billing', 'accounts'],
    notes: 'Offset printing client needing simple billing with accounts.',
  },
  {
    code: 103,
    slug: 'cotton_knits',
    name: 'Cotton Knits Fashion',
    corporateId: 'COTTON_KNITS',
    industry: 'garment_manufacturing',
    industryName: 'Garment Manufacturing',
    database: 'cotton_knits_db',
    domains: ['cotton.codexsun.com', 'cottonknits.codexsun.com', 'cotton.local'],
    companies: ['Cotton Knits Fashion'],
    apps: ['application', 'billing', 'accounts', 'inventory', 'garment'],
    landingApp: 'billing',
    requirements: ['billing', 'accounts', 'einvoice', 'eway'],
    notes: 'Garment manufacturing client needing billing, accounts, e-invoice, and e-way.',
  },
  {
    code: 104,
    slug: 'sathasivam_garments',
    name: 'Sathasivam Garment Group',
    corporateId: 'SATHASIVAM',
    industry: 'garment_manufacturing',
    industryName: 'Garment Manufacturing',
    database: 'sathasivam_garments_db',
    domains: ['sukraa.codexsun.com', 'mathan.codexsun.com', 'sukraa.local'],
    companies: ['Sukraa Garments', 'Mathan Knitters'],
    apps: ['application', 'billing', 'accounts', 'inventory', 'garment'],
    landingApp: 'billing',
    requirements: ['billing', 'accounts', 'einvoice', 'eway'],
    notes: 'One client tenant with two companies: Sukraa Garments and Mathan Knitters.',
  },
  {
    code: 105,
    slug: 'poly_made_india',
    name: 'Poly Made India',
    corporateId: 'POLY_MADE_INDIA',
    industry: 'fabric_trading',
    industryName: 'Fabric Trading',
    database: 'poly_made_india_db',
    domains: ['polymade.codexsun.com'],
    companies: ['Poly Made India'],
    apps: ['application', 'billing', 'accounts', 'inventory'],
    landingApp: 'billing',
    requirements: ['billing', 'accounts', 'einvoice', 'eway'],
    notes: 'Fabric trader needing billing, accounts, e-invoice, and e-way.',
  },
  {
    code: 106,
    slug: 'amal_tex',
    name: 'Amal Tex',
    corporateId: 'AMAL_TEX',
    industry: 'garment_manufacturing',
    industryName: 'Garment Manufacturing',
    database: 'amal_tex_db',
    domains: ['amaltex.codexsun.com', 'amaltex.local'],
    companies: ['Amal Tex'],
    apps: ['application', 'billing', 'accounts', 'inventory', 'garment'],
    landingApp: 'billing',
    requirements: ['billing', 'accounts', 'einvoice', 'eway'],
    notes: 'Garment manufacturing client needing billing, accounts, e-invoice, and e-way.',
  },
  {
    code: 107,
    slug: 'kgs_printing',
    name: 'KGS Printing',
    corporateId: 'KGS_PRINTING',
    industry: 'offset_printing',
    industryName: 'Offset Printing',
    database: 'kgs_printing_db',
    domains: ['kgsprinting.codexsun.com'],
    companies: ['KGS Printing'],
    apps: ['application', 'billing', 'accounts', 'inventory', 'offset'],
    landingApp: 'billing',
    requirements: ['simple-billing', 'accounts'],
    notes: 'Offset printing client needing simple billing with accounts.',
  },
  {
    code: 108,
    slug: 'thirumurugan_printers',
    name: 'Thirumurugan Printers',
    corporateId: 'THIRUMURUGAN_PRINTERS',
    industry: 'offset_printing',
    industryName: 'Offset Printing',
    database: 'thirumurugan_printers_db',
    domains: ['thirumurugan.codexsun.com'],
    companies: ['Thirumurugan Printers'],
    apps: ['application', 'billing', 'accounts', 'inventory', 'offset'],
    landingApp: 'billing',
    requirements: ['simple-billing', 'accounts'],
    notes: 'Offset printing client needing simple billing with accounts.',
  },
  {
    code: 109,
    slug: 'sms_upvc',
    name: 'SMS UPVC',
    corporateId: 'SMS_UPVC',
    industry: 'upvc',
    industryName: 'UPVC',
    database: 'sms_upvc_db',
    domains: ['smsupvc.codexsun.com', 'smsupvc.local'],
    companies: ['SMS UPVC'],
    apps: ['application', 'billing', 'accounts', 'inventory'],
    landingApp: 'billing',
    requirements: ['simple-billing', 'accounts', 'eway'],
    notes: 'UPVC client needing simple billing, accounts, and e-way.',
  },
  {
    code: 110,
    slug: 'tirupur_direct',
    name: 'Tirupur Direct',
    corporateId: 'TIRUPUR_DIRECT',
    industry: 'ecommerce',
    industryName: 'Ecommerce / Garments Sales',
    database: 'tirupur_direct_db',
    domains: ['tirupurdirect.codexsun.com', 'tirupurdirect.local'],
    companies: ['Tirupur Direct'],
    apps: ['application', 'billing', 'accounts', 'inventory', 'ecommerce', 'sites'],
    landingApp: 'ecommerce',
    requirements: ['ecommerce', 'garments-sales', 'billing', 'inventory'],
    notes: 'Tirupur-based garments ecommerce sales tenant.',
  },
  {
    code: 111,
    slug: 'deal_o_deal',
    name: 'Deal O Deal',
    corporateId: 'DEAL_O_DEAL',
    industry: 'ecommerce',
    industryName: 'Ecommerce / Computer Seconds Store',
    database: 'deal_o_deal_db',
    domains: ['dealodeal.codexsun.com'],
    companies: ['Deal O Deal'],
    apps: ['application', 'billing', 'accounts', 'inventory', 'ecommerce', 'sites'],
    landingApp: 'ecommerce',
    requirements: ['ecommerce', 'computer-seconds-store', 'billing', 'inventory'],
    notes: 'Computer seconds store ecommerce tenant.',
  },
  {
    code: 112,
    slug: 'tenkasi_sports',
    name: 'Tenkasi Sports',
    corporateId: 'TENKASI_SPORTS',
    industry: 'sports_club',
    industryName: 'Sports Club',
    database: 'tenkasi_sports_db',
    domains: ['tenkasisports.codexsun.com', 'tenkasisports.local'],
    companies: ['Tenkasi Sports'],
    apps: ['application', 'billing', 'taskmanager', 'sports-club'],
    landingApp: 'sports-club',
    requirements: ['students', 'masters', 'subscriptions', 'attendance'],
    notes: 'Sports club tenant to manage students and masters.',
  },
  {
    code: 113,
    slug: 'altexlabs',
    name: 'Altexlabs',
    corporateId: 'ALTEXLABS',
    industry: 'garment_testing_lab',
    industryName: 'Garment Testing Lab',
    database: 'altexlabs_db',
    domains: ['altexlabs.codexsun.com'],
    companies: ['Altexlabs'],
    apps: ['application', 'billing', 'taskmanager', 'media', 'testing-lab'],
    landingApp: 'testing-lab',
    requirements: ['testing-reports', 'customer-files', 'lab-workflow'],
    notes: 'Garment testing lab needing testing report workflow.',
  },
  {
    code: 114,
    slug: 'aaran_business_connect',
    name: 'Aaran Business Connect',
    corporateId: 'AARAN_BUSINESS_CONNECT',
    industry: 'business_connect',
    industryName: 'Business Connect',
    database: 'aaran_business_connect_db',
    domains: ['business.codexsun.com', 'connect.codexsun.com', 'aaranconnect.local'],
    companies: ['Aaran Business Connect'],
    apps: ['application', 'crm', 'sites', 'business-connect'],
    landingApp: 'business-connect',
    requirements: ['business-directory', 'lead-connect', 'india-mart-style'],
    notes: 'Business people connection platform, similar in spirit to IndiaMART.',
  },
]

export const localClientHostnames = Array.from(new Set(liveClientScopes.flatMap((client) => client.domains))).sort()
