name: cxsun

services:
  cxsun:
    build:
      context: ..
      dockerfile: .container/Dockerfile
    image: cxsun:v1
    container_name: cxsun
    restart: unless-stopped
    environment:
      GIT_REPO_URL: ${GIT_REPO_URL:-https://github.com/CODEXSUN/cxsun.git}
      GIT_BRANCH: ${GIT_BRANCH:-main}
      GIT_PULL_ON_START: ${GIT_PULL_ON_START:-false}
      APP_DIR: /workspace/cxsun
      HOST: 0.0.0.0
      PORT: ${PORT:-6005}
      VITE_PORT: ${VITE_PORT:-6010}
      VITE_API_BASE_URL: ${VITE_API_BASE_URL:-https://codexsun.com}
      FRONTEND_URL: ${FRONTEND_URL:-https://codexsun.com}
      CORS_ORIGINS: ${CORS_ORIGINS:-https://codexsun.com,https://www.codexsun.com}
      DB_HOST: ${DB_HOST:-mariadb}
      DB_PORT: ${DB_PORT:-3306}
      DB_NAME: ${DB_NAME:-cxsun_master}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-DbPass1@@}
      JWT_SECRET: ${JWT_SECRET:-}
      SUPER_ADMIN_NAME: ${SUPER_ADMIN_NAME:-}
      SUPER_ADMIN_EMAIL: ${SUPER_ADMIN_EMAIL:-}
      SUPER_ADMIN_PASSWORD: ${SUPER_ADMIN_PASSWORD:-}
      SOFTWARE_ADMIN_NAME: ${SOFTWARE_ADMIN_NAME:-}
      SOFTWARE_ADMIN_EMAIL: ${SOFTWARE_ADMIN_EMAIL:-}
      SOFTWARE_ADMIN_PASSWORD: ${SOFTWARE_ADMIN_PASSWORD:-}
      TENANT_ADMIN_NAME: ${TENANT_ADMIN_NAME:-}
      TENANT_ADMIN_EMAIL: ${TENANT_ADMIN_EMAIL:-}
      TENANT_ADMIN_PASSWORD: ${TENANT_ADMIN_PASSWORD:-}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      REDIS_DB: ${REDIS_DB:-0}
      REDIS_TLS: ${REDIS_TLS:-false}
      QUEUE_ENABLED: ${QUEUE_ENABLED:-true}
      DATABASE_BACKUP_INTERVAL_HOURS: ${DATABASE_BACKUP_INTERVAL_HOURS:-6}
    ports:
      - "${PORT:-6005}:${PORT:-6005}"
      - "${VITE_PORT:-6010}:${VITE_PORT:-6010}"
    volumes:
      - cxsun-volume:/workspace
    networks:
      - codexion-network

volumes:
  cxsun-volume:
    name: cxsun-volume

networks:
  codexion-network:
    external: true
